services:
  nginx:
    build: ./nginx
    ports:
      - "8090:8090"
      - "8008:8008"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
